### ISSUE TITLE
Samples were not loaded correctly error when loading a specific record from the mimic3wdb-matched database

### ISSUE THREAD

**Issue by thomasdziedzic-calmwave** [MIT-LCP/wfdb-python#430] opened 2022-11-02 23:56 UTC
Minimal test case:

```python
import wfdb
line = 'p08/p086831/p086831-2130-12-29-18-28n'
line_parts = line.strip().split('/')
record = wfdb.rdrecord(line_parts[2], pn_dir=f'mimic3wdb-matched/{line_parts[0]}/{line_parts[1]}')
```

All other records from the mimic3wdb-matched database seem to process correctly so far

Trace:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [3], line 3
      1 line = 'p08/p086831/p086831-2130-12-29-18-28n'
      2 line_parts = line.strip().split('/')
----> 3 record = wfdb.rdrecord(line_parts[2], pn_dir=f'mimic3wdb-matched/{line_parts[0]}/{line_parts[1]}')

File ~/Library/Caches/pypoetry/virtualenvs/mimic3-waveform-matched-snowflake-etl-26HBJIJO-py3.10/lib/python3.10/site-packages/wfdb/io/record.py:2065, in rdrecord(record_name, sampfrom, sampto, channels, physical, pn_dir, m2s, smooth_frames, ignore_skew, return_res, force_channels, channel_names, warn_empty)
   2062 no_file = False
   2063 sig_data = None
-> 2065 record.e_d_signal = _signal._rd_segment(
   2066     file_name=record.file_name,
   2067     dir_name=dir_name,
   2068     pn_dir=pn_dir,
   2069     fmt=record.fmt,
   2070     n_sig=record.n_sig,
   2071     sig_len=record.sig_len,
   2072     byte_offset=record.byte_offset,
   2073     samps_per_frame=record.samps_per_frame,
   2074     skew=record.skew,
   2075     init_value=record.init_value,
   2076     sampfrom=sampfrom,
   2077     sampto=sampto,
   2078     channels=channels,
   2079     ignore_skew=ignore_skew,
   2080     no_file=no_file,
   2081     sig_data=sig_data,
   2082     return_res=return_res,
   2083 )
   2085 # Only 1 sample/frame, or frames are smoothed. Return uniform numpy array
   2086 if smooth_frames:
   2087     # Arrange/edit the object fields to reflect user channel
   2088     # and/or signal range input

File ~/Library/Caches/pypoetry/virtualenvs/mimic3-waveform-matched-snowflake-etl-26HBJIJO-py3.10/lib/python3.10/site-packages/wfdb/io/_signal.py:1202, in _rd_segment(file_name, dir_name, pn_dir, fmt, n_sig, sig_len, byte_offset, samps_per_frame, skew, init_value, sampfrom, sampto, channels, ignore_skew, no_file, sig_data, return_res)
   1198 signals = [None] * len(channels)
   1200 for fn in w_file_name:
   1201     # Get the list of all signals contained in the dat file
-> 1202     datsignals = _rd_dat_signals(
   1203         file_name=fn,
   1204         dir_name=dir_name,
   1205         pn_dir=pn_dir,
   1206         fmt=w_fmt[fn],
   1207         n_sig=len(datchannel[fn]),
   1208         sig_len=sig_len,
   1209         byte_offset=w_byte_offset[fn],
   1210         samps_per_frame=w_samps_per_frame[fn],
   1211         skew=w_skew[fn],
   1212         init_value=w_init_value[fn],
   1213         sampfrom=sampfrom,
   1214         sampto=sampto,
   1215         no_file=no_file,
   1216         sig_data=sig_data,
   1217     )
   1219     # Copy over the wanted signals
   1220     for cn in range(len(out_dat_channel[fn])):

File ~/Library/Caches/pypoetry/virtualenvs/mimic3-waveform-matched-snowflake-etl-26HBJIJO-py3.10/lib/python3.10/site-packages/wfdb/io/_signal.py:1433, in _rd_dat_signals(file_name, dir_name, pn_dir, fmt, n_sig, sig_len, byte_offset, samps_per_frame, skew, init_value, sampfrom, sampto, no_file, sig_data)
   1428 signal = _skew_sig(
   1429     signal, skew, n_sig, read_len, fmt, nan_replace, samps_per_frame
   1430 )
   1432 # Integrity check of signal shape after reading
-> 1433 _check_sig_dims(signal, read_len, n_sig, samps_per_frame)
   1435 return signal

File ~/Library/Caches/pypoetry/virtualenvs/mimic3-waveform-matched-snowflake-etl-26HBJIJO-py3.10/lib/python3.10/site-packages/wfdb/io/_signal.py:2047, in _check_sig_dims(sig, read_len, n_sig, samps_per_frame)
   2045 for ch in range(n_sig):
   2046     if len(sig[ch]) != samps_per_frame[ch] * read_len:
-> 2047         raise ValueError("Samples were not loaded correctly")

ValueError: Samples were not loaded correctly
```

**Comment by bemoody** [comment] 2022-11-08 18:00
That's very weird.  Thanks for pointing it out.

It's not a bug in wfdb-python - it's a bug in the database.  Compare `p086831-2130-12-29-18-28n.hea` with `3855262n.hea`; it looks like the record has only 17 signals and somehow an extra signal got stuck in there when generating the matched header.  I have no idea how that could have happened.

This should probably be reported at: https://github.com/MIT-LCP/mimic-code/issues

**Comment by tompollard** [comment] 2022-11-08 19:29
Now raised at https://github.com/MIT-LCP/mimic-code/issues/1422. Thanks @thomasdziedzic-calmwave, I'll close the issue here.

**Closed by tompollard** 2022-11-08 19:29 UTC
